### ISSUE TITLE
Feature Request: View Video Option

### ISSUE THREAD

**Issue by pxsmith** [danielravina/headset#3]
Say I’m listening through an artist’s videos on Headset, and there’s a particularly interesting video. It’d be great to be able to jump right to the video, then get back into audio-only after it’s over.

**Comment by danielravina** [comment]
done in this version: https://github.com/danielravina/headset-electron/releases/download/v1.3.0/Headset.1.3.0.zip

according to YT's policy, the video can't be switched off or hidden. But it is minimized so you can jump to see the video at any time.
