### ISSUE TITLE
Feature Request: Play/Pause Hotkey

### ISSUE THREAD

**Issue by pxsmith** [danielravina/headset#4]
cc: @danielravina What’s up, Doc? Can you make `spacebar` a hotkey for play/pause toggling when they app is in focus? This is pretty standard in music players.

**Comment by danielravina** [comment]
Done, it's in the current version. Plus a sweet radio 📻 feature!

**Comment by pxsmith** [comment]
@danielravina WOAH! That radio feature looks 🔥

**Comment by pxsmith** [comment]
@danielravina I found a bug related to this—if I’m searching and hit `space` then the current song plays/pauses.

If a text input field is active, the hotkey should be disabled.

**Comment by danielravina** [comment]
Lol. Nice catch Smith. Thanks for reporting!

**Comment by danielravina** [comment]
Fixed 👍
